# Generated by Django 4.0.4 on 2022-05-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scens',
            new_name='Scenes',
        ),
    ]
