# Generated by Django 4.0.4 on 2022-05-05 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0002_rename_scens_scenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('sentence', models.CharField(max_length=400)),
                ('order', models.IntegerField(unique=True)),
                ('created_at', models.DateField(db_index=True, default=datetime.date.today)),
                ('scens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='france.scenes')),
            ],
            options={
                'ordering': ('scens', 'order'),
            },
        ),
    ]
