# Generated by Django 4.0.4 on 2022-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0003_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='sentence',
            field=models.TextField(max_length=400),
        ),
    ]
