# Generated by Django 4.0.4 on 2022-05-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0005_alter_phrase_options_rename_scens_phrase_scenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_pl', models.CharField(max_length=100)),
                ('world_fr', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('phonetic', models.CharField(max_length=100)),
                ('scenes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='france.scenes')),
            ],
            options={
                'ordering': ('world_pl', 'world_fr'),
            },
        ),
    ]
