# Generated by Django 4.0.4 on 2022-05-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0007_alter_phrase_order_alter_world_scenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='scenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='france.scenes'),
        ),
    ]
