# Generated by Django 4.0.4 on 2022-05-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('france', '0008_alter_phrase_scenes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='World',
            new_name='Word',
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('word_pl', 'word_fr')},
        ),
        migrations.RenameField(
            model_name='word',
            old_name='world_fr',
            new_name='word_fr',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='world_pl',
            new_name='word_pl',
        ),
    ]
